### ISSUE TITLE
 Can't connect to twilsock...

### ISSUE THREAD

**Issue by vipulphysiofirst** [twilio/TwilioChatJsReactNative#45]
i m getting the token from 
try {
const token = new AccessToken(twilioAccountSid, twilioApiKey, twilioApiSecret);
var tok = token.toJwt();
// but when i intialize the client with proper crednetial not test credential i am getting this error 
 let client = await Chat.Client.create(tok);
} catch (e){
      console.log(e);
}

**Comment by vipulphysiofirst** [comment]
ransportUnavailableError: Can't connect to twilsock
    at Upstream.send (C:\Users\vipul\github\physiofirst\backend\node_modules\twilsock\lib\services\upstream.js:149:35)
    at TwilsockClient.post (C:\Users\vipul\github\physiofirst\backend\node_modules\twilsock\lib\client.js:176:30)
    at C:\Users\vipul\github\physiofirst\backend\node_modules\twilio-sync\lib\services\network.js:121:59
    at Retrier.<anonymous> (C:\Users\vipul\github\physiofirst\backend\node_modules\twilio-sync\lib\services\network.js:79:17)
    at Retrier.emit (events.js:203:13)
    at Retrier.EventEmitter.emit (domain.js:476:20)
    at Retrier.attempt (C:\Users\vipul\github\physiofirst\backend\node_modules\operation-retrier\lib\retrier.js:28:14)
    at Timeout.<anonymous> (C:\Users\vipul\github\physiofirst\backend\node_modules\operation-retrier\lib\retrier.js:72:46)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:12396) UnhandledPromiseRejectionWarning: Error: Can't connect to twilsock
    at Upstream.send (C:\Users\vipul\github\physiofirst\backend\node_modules\twilsock\lib\services\upstream.js:149:35)
    at TwilsockClient.post (C:\Users\vipul\github\physiofirst\backend\node_modules\twilsock\lib\client.js:176:30)
    at C:\Users\vipul\github\physiofirst\backend\node_modules\twilio-sync\lib\services\network.js:121:59
    at Retrier.<anonymous> (C:\Users\vipul\github\physiofirst\backend\node_modules\twilio-sync\lib\services\network.js:79:17)
    at Retrier.emit (events.js:203:13)
    at Retrier.EventEmitter.emit (domain.js:476:20)
    at Retrier.attempt (C:\Users\vipul\github\physiofirst\backend\node_modules\operation-retrier\lib\retrier.js:28:14)
    at Timeout.<anonymous> (C:\Users\vipul\github\physiofirst\backend\node_modules\operation-retrier\lib\retrier.js:72:46)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:12396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12396) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12396) UnhandledPromiseRejectionWarning: Error: Can't connect to twilsock
    at Upstream.send (C:\Users\vipul\github\physiofirst\backend\node_modules\twilsock\lib\services\upstream.js:149:35)
    at TwilsockClient.post (C:\Users\vipul\github\physiofirst\backend\node_modules\twilsock\lib\client.js:176:30)
    at C:\Users\vipul\github\physiofirst\backend\node_modules\twilio-sync\lib\services\network.js:121:59
    at Retrier.<anonymous> (C:\Users\vipul\github\physiofirst\backend\node_modules\twilio-sync\lib\services\network.js:79:17)
    at Retrier.emit (events.js:203:13)
    at Retrier.EventEmitter.emit (domain.js:476:20)
    at Retrier.attempt (C:\Users\vipul\github\physiofirst\backend\node_modules\operation-retrier\lib\retrier.js:28:14)
    at Timeout.<anonymous> (C:\Users\vipul\github\physiofirst\backend\node_modules\operation-retrier\lib\retrier.js:72:46)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:12396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
GET /api/users/token - - ms - -

**Comment by berkus** [comment]
Please try updating to the latest twilio-chat version, it provides better error messages when failing to connect.

Feel free to post a new one after you've upgraded if it still doesn't work.
